apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: node:9.2.1
        command: ['/bin/sh', '-c']
        args: ['cd /home && git clone https://github.com/iuriifavi/current_com.git && cd current_com && npm install && sails lift']
        name: web
        ports:
        - containerPort: 1337
          name: http-server